### ISSUE TITLE
Failure on trying to translate an N nucleotide

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/isovar#17]
`cdna_sequence_from_first_codon.translate()` throws a `NotImplementedError` for this `VariantSequence`:

`VariantSequence(prefix=u'CTGCTGTCCTCCAGGCTGGGCTCAGGGAGGGGC', alt='A', suffix=u'AGGCTGGACCGGAN', full_sequence=u'CTGCTGTCCTCCAGGCTGGGCTCAGGGAGGGGCAAGGCTGGACCGGAN', read_names=set(['K00193:50:H5NKVBBXX:5:2222:6522:48913', 'K00193:50:H5NKVBBXX:5:2105:32522:47225', 'K00193:50:H5NKVBBXX:5:2101:32583:40192', 'K00193:50:H5NKVBBXX:5:1102:32765:39066']), read_count=4)`

Not sure what the right behavior is?

**Comment by iskandr** [comment]
I'm not sure either. Seems like a waste to drop reads with 'N' altogether, maybe I could trim the sequence between the left-most and right-most N? 

Alternatively, I could try to match that sequence against another without the 'N' and add those reads as partially supporting (which implies a weight to count partially supporting reads was in the first prototype but doesn't exist in this code).

**Comment by JPFinnigan** [comment]
> Alternatively, I could try to match that sequence against another without the 'N' and add those reads as partially supporting (which implies a weight to count partially supporting reads was in the first prototype but doesn't exist in this code).

This is a cool idea. One could think about the problem of determining the sequence of a variant containing transcript in a probabilistic way where the idea is to build up certainty for each base-call around a variant. If that's the framework, then there's also no reason to limit read sequence comparisons w/in a given exon to the RNASeq reads if WES/WGS data are available for the same sample. Reads that only partially overlap the ~100bp window around a variant then become more helpful because they can be used to build up evidence for flanking sequences.
