### ISSUE TITLE
scikit-bio 0.5.0 is not compatible with py2

### ISSUE THREAD

**Issue by arahuja** [hammerlab/isovar#27]
`scikit-bio 0.5.0` was uploaded to PyPI on 2016-06-14

> Note: scikit-bio is no longer compatible with Python 2. scikit-bio is compatible with Python 3.4 and later.

Do you want to fix the version to be `0.4.2` then?

**Comment by tavinathanson** [comment]
Interesting move by `scikit-bio`; context: https://github.com/biocore/scikit-bio-rfcs/pull/6 https://github.com/biocore/scikit-bio/pull/1315

Thoughts on dropping `py2`?

**Comment by hammer** [comment]
> Thoughts on dropping py2?

I'd be pro dropping Python though!

**Comment by iskandr** [comment]
@tavinathanson I've been using almost exclusively py3 for the past year and I don't love the unicode mixups and verbosity of py2+py3 development, but it would probably frustrate a lot of potential users to drop py2 (since 80-95% of Python users are still on py2). I don't want to get into the business of policing the flawed Python Version Bump. 

We should probably drop skbio and either switch to Bio.Python or write something lighter-weight for dealing with DNA, amino acids, and translations between the two.

**Comment by tavinathanson** [comment]
> I don't want to get into the business of policing the flawed Python Version Bump.

I think this is a solid argument against dropping py2.

I like the idea of writing something lighter-weight instead of relying on huge libraries for minimal functionality.
